#!/usr/bin/bash
#DEPENDENCY:samtools/*
#DEPENDENCY:bedtools/*
#DEPENDENCY:mashmap/*
#DEPENDENCY:data-genome/grch38-gencode
#DEPENDENCY:data-transcriptome/grch38-gencode47
#DEPENDENCY:data-gtf/grch38-gencode47
#WHATIS:GRCh38 GENCODE 47 gentrome FASTA for pseudoalignment

#########################################################
# GRCh38 GENCODE 47 gentrome FASTA for pseudoalignment
# - https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode
#########################################################

install_app() {
    module load samtools
    module load bedtools
    module load mashmap
    module load data-genome/grch38-gencode
    module load data-transcriptome/grch38-gencode47
    module load data-gtf/grch38-gencode47

    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"

    url="https://raw.githubusercontent.com/COMBINE-lab/SalmonTools/refs/heads/master/scripts/generateDecoyTranscriptome.sh"
    print_stderr "Downloading gentrome generation script for ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "generateDecoyTranscriptome.sh" "$url"

    print_stderr "Generating gentrome FASTA and decoy TEXT for ${YELLOW}${app_name_version}${NC}"
    bash generateDecoyTranscriptome.sh \
        -j $ncpu \
        -a "$ANNOTATION_GTF" \
        -g "$GENOME_FASTA" \
        -t "$TRANSCRIPT_FASTA" \
        -o "$target_dir"
    
    print_stderr "Indexing ${YELLOW}${app_name_version}${NC} with samtools faidx"
    samtools faidx "$target_dir/gentrome.fa"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    remove_default_dependencies "samtools"
    remove_default_dependencies "bedtools"
    remove_default_dependencies "mashmap"
    remove_default_dependencies "data" # remove all data dependencies
    
    # add custom environment variables and functions to modulefile
    cat << EOF >> "${script_path}"
set gentrome_fasta \$ref_root/gentrome.fa
set decoys_txt \$ref_root/decoys.txt
setenv GENTROME_FASTA \$gentrome_fasta
setenv DECOYS_TXT \$decoys_txt

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    puts stderr "Available environment variables:"
    puts stderr "  GENTROME_FASTA       (gentrome fasta file)"
    puts stderr "  DECOYS_TXT           (decoys text file)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local gentrome_fasta = pathJoin(ref_root, "gentrome.fa")
local decoys_txt = pathJoin(ref_root, "decoys.txt")
setenv("GENTROME_FASTA", gentrome_fasta)
setenv("DECOYS_TXT", decoys_txt)

if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  GENTROME_FASTA       (gentrome fasta file)\n")
    io.stderr:write("  DECOYS_TXT           (decoys text file)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
