#!/usr/bin/bash
#DEPENDENCY:ref-grcm39/fasta-genome-gencode
#DEPENDENCY:ref-grcm39/gtf-gencodeM36
#DEPENDENCY:star/*
#WHATIS:STAR GRCm39 GENCODE M36 index for read length 101

#########################################################
# STAR GRCm39 GENCODE M36 index for read length 101
# --sjdbOverhang 100 # read length -1
#########################################################

install_app() {
    # mkdir -p "$target_base_dir"  # modules/apps/name
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    
    module load ref-grcm39/fasta-genome-gencode
    module load ref-grcm39/gtf-gencodeM36
    module load star

    print_stderr "Building STAR index for ${YELLOW}${app_name_version}${NC}"
    STAR --runThreadN "${ncpu}" \
        --runMode genomeGenerate \
        --genomeDir "$target_dir" \
        --genomeFastaFiles "$GENOME_FASTA" \
        --sjdbGTFfile "$ANNOTATION_GTF" \
        --sjdbOverhang 100
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # app_root is a special variable that points to the app directory in modulefile[.lua]

    # remove star dependency added by default (because you may not want the version used to build the index)
    sed -i '/^# Dependency: star\//d' "${script_path}"
    sed -i "/^module load star\//d" "${script_path}"
    sed -i "/^-- Dependency: star\//d" "${script_path}.lua"
    sed -i "/^depends_on(\"star\//d" "${script_path}.lua"

    # add custom environment variables and functions to modulefile
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set star_index_dir \$ref_root
setenv STAR_INDEX_DIR \$star_index_dir
if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    # only display message when in terminal
    if {[info exists env(TERM)] && \$env(TERM) != "dumb"} {
        puts stderr "Available environment variables:"
        puts stderr "  STAR_INDEX_DIR       (STAR index directory)"
    }
}
EOF

    cat << EOF >> "${script_path}.lua"
local star_index_dir = ref_root
setenv("STAR_INDEX_DIR", star_index_dir)
if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    -- only display message when in terminal
    if os.getenv("TERM") and os.getenv("TERM") ~= "dumb" then
        io.stderr:write("Available environment variables:\n")
        io.stderr:write("  STAR_INDEX_DIR       (STAR index directory)\n")
    end
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
