#!/usr/bin/bash
#WHATIS:Cell Ranger GRCm39 2024-A index

#########################################################
# Cell Ranger GRCm39 2024-A index
# - https://www.10xgenomics.com/support/software/cell-ranger/downloads#reference-downloads
# Download the pre-built Cell Ranger reference for GRCm39 2024-A
#########################################################

install_app() {
    # mkdir -p "$target_base_dir"  # modules/apps/name
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"

    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    url="https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCm39-2024-A.tar.gz"
    wget -nv -O "refdata-gex.tar.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    tar -xzf "refdata-gex.tar.gz" -C "$target_dir" --strip-components=1
}

special_modulefiles() {
    # add custom environment variables and functions to modulefile
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set cellranger_ref_dir \$ref_root
setenv CELLRANGER_REF_DIR \$cellranger_ref_dir
set genome_fasta \$cellranger_ref_dir/fasta/genome.fa
setenv GENOME_FASTA \$genome_fasta
set genome_fasta_fai \$cellranger_ref_dir/fasta/genome.fa.fai
setenv GENOME_FASTA_FAI \$genome_fasta_fai
set annotation_gtf_gz \$cellranger_ref_dir/genes/genes.gtf.gz
setenv ANNOTATION_GTF_GZ \$annotation_gtf_gz
set star_index_dir \$cellranger_ref_dir/star
setenv STAR_INDEX_DIR \$star_index_dir

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    # Hide help messages in the SLURM environment
    if {![info exists ::env(SLURM_JOB_ID)]} {
        puts stderr "Available environment variables:"
        puts stderr "  CELLRANGER_REF_DIR (reference directory: cellranger)"
        puts stderr "  GENOME_FASTA       (fasta file)"
        puts stderr "  GENOME_FASTA_FAI   (fasta fai index)"
        puts stderr "  ANNOTATION_GTF_GZ  (annotation gtf.gz: gene counting)"
        puts stderr "  STAR_INDEX_DIR     (star index: star alignment)"
    }
}
EOF

    cat << EOF >> "${script_path}.lua"
local cellranger_ref_dir = ref_root
setenv("CELLRANGER_REF_DIR", cellranger_ref_dir)
local genome_fasta = pathJoin(cellranger_ref_dir, "fasta/genome.fa")
setenv("GENOME_FASTA", genome_fasta)
local genome_fasta_fai = pathJoin(cellranger_ref_dir, "fasta/genome.fa.fai")
setenv("GENOME_FASTA_FAI", genome_fasta_fai)
local annotation_gtf_gz = pathJoin(cellranger_ref_dir, "genes/genes.gtf.gz")
setenv("ANNOTATION_GTF_GZ", annotation_gtf_gz)
local star_index_dir = pathJoin(cellranger_ref_dir, "star")
setenv("STAR_INDEX_DIR", star_index_dir)
if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    -- Hide help messages in the SLURM environment
    if os.getenv("SLURM_JOB_ID") == nil then
        io.stderr:write("Available environment variables:\n")
        io.stderr:write(string.format("  CELLRANGER_REF_DIR (reference directory: cellranger)\n", cellranger_ref_dir))
        io.stderr:write(string.format("  GENOME_FASTA       (fasta file)\n", genome_fasta))
        io.stderr:write(string.format("  GENOME_FASTA_FAI   (fasta fai index)\n", genome_fasta_fai))
        io.stderr:write(string.format("  ANNOTATION_GTF_GZ  (annotation gtf.gz: gene counting)\n", annotation_gtf_gz))
        io.stderr:write(string.format("  STAR_INDEX_DIR     (star index: star alignment)\n", star_index_dir))
    end
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
