#!/usr/bin/bash
#DEPENDENCY:data-genome/grch38-gencode
#DEPENDENCY:data-transcriptome/grch38-gencode47
#DEPENDENCY:salmon/*
#WHATIS:Salmon GRCh38 GENCODE 47 index for transcript quantification

#########################################################
# If you want to build index for another annotation version,
#   1. copy the script to a new name, e.g., salmon-grch38-gencode49
#   2. change the dependencies to the new genome and transcriptome data
#   3. change the WHATIS line accordingly
#
# - https://combine-lab.github.io/salmon/
# - https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode
#########################################################

install_app() {
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    
    print_stderr "Appending genome to transcriptome and generating decoys..."
    cat \
        "$TRANSCRIPT_FASTA" \
        "$GENOME_FASTA" \
        > gentrome.fa
    
    cat "$GENOME_FASTA" | \
        grep "^>" | \
        cut -d " " -f 1 | \
        sed 's/^>//' \
        > decoys.txt

    print_stderr "Building Salmon index for ${YELLOW}${app_name_version}${NC}"
    salmon index \
        -p $ncpu \
        -t gentrome.fa \
        -d decoys.txt \
        -i "$target_dir" \
        --gencode
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # app_root is a special variable that points to the app directory in modulefile[.lua]
    remove_default_dependencies "salmon"
    remove_default_dependencies "data"

    # add custom environment variables and functions to modulefile
    # app_root is a special variable that points to the app directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set salmon_index_dir \$app_root
setenv SALMON_INDEX_DIR \$salmon_index_dir
if { [module-info mode] == "load" } {
    puts stderr "Available environment variables:"
    puts stderr "  SALMON_INDEX_DIR       (Salmon index directory)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local salmon_index_dir = app_root
setenv("SALMON_INDEX_DIR", salmon_index_dir)
if (mode() == "load") then
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  SALMON_INDEX_DIR       (Salmon index directory)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
