#!/usr/bin/bash
#DEPENDENCY:data-genome/grch38-gencode
#DEPENDENCY:data-gtf/grch38-gencode47
#DEPENDENCY:data-vcf/grch38-hprc-v1.1-decomposed-gencode
#DEPENDENCY:vg/*
#WHATIS:VG graph genome with GRCh38 and GENCODE47

#########################################################
# VG graph genome with GRCh38 and GENCODE47
# Using HPRC v1.1 variants (decomposed) to build the graph
# - VG is a graph genome toolkit
# - The RNA-seq results can be parsed by rpvg after mapping with VG
#########################################################

install_app() {
    # mkdir -p "$target_base_dir"  # modules/apps/name
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    mkdir -p vg-tmp
    
    module load data-genome/grch38-gencode
    module load data-gtf/grch38-gencode47
    module load data-vcf/grch38-hprc-v1.1-decomposed-gencode
    module load vg

    print_stderr "Building VG graph index for ${YELLOW}${app_name_version}${NC}"
    vg autoindex --workflow mpmap --workflow rpvg \
        --prefix hprc-v1.1-mc-grch38-gencode47 \
        --ref-fasta $GENOME_FASTA \
        --tx-gff $ANNOTATION_GTF \
        --vcf $HPRC_GENCODE_VCF_GZ \
        --threads $ncpu \
        --target-mem 400G \
        --tmp-dir vg-tmp \
        --gcsa-size-limit 4398046511104 \
        --verbosity 2
    # 32 threads are recommended
    # You should allocate at least 400GB memory for building the graph
    # 4TB for gcsa-size-limit (increase temporary limit when building GCSA)

    print_stderr "Moving VG graph index files to target directory"
    mv hprc-v1.1-mc-grch38-gencode47.* "$target_dir/"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # app_root is a special variable that points to the app directory in modulefile[.lua]
    remove_default_dependencies "vg"
    remove_default_dependencies "data"

    # add custom environment variables and functions to modulefile
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set vg_xg \$ref_root/hprc-v1.1-mc-grch38-gencode47.spliced.xg
set vg_dist \$ref_root/hprc-v1.1-mc-grch38-gencode47.spliced.dist
set vg_gcsa \$ref_root/hprc-v1.1-mc-grch38-gencode47.spliced.gcsa
set vg_gcsa_lcp \$ref_root/hprc-v1.1-mc-grch38-gencode47.spliced.gcsa.lcp
set vg_gbwt \$ref_root/hprc-v1.1-mc-grch38-gencode47.haplotx.gbwt
set vg_gbwt_ri \$ref_root/hprc-v1.1-mc-grch38-gencode47.haplotx.gbwt.ri
set vg_txorigin_tsv \$ref_root/hprc-v1.1-mc-grch38-gencode47.txorigin.tsv

setenv VG_XG \$vg_xg
setenv VG_DIST \$vg_dist
setenv VG_GCSA \$vg_gcsa
setenv VG_GCSA_LCP \$vg_gcsa_lcp
setenv VG_GBWT \$vg_gbwt
setenv VG_GBWT_RI \$vg_gbwt_ri
setenv VG_TXORIGIN_TSV \$vg_txorigin_tsv

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    puts stderr "Available environment variables:"
    puts stderr "  VG_XG       (xg index file: mpmap, rpvg)"
    puts stderr "  VG_DIST     (dist index file: mpmap)"
    puts stderr "  VG_GCSA     (gcsa2 index file: mpmap, rpvg)"
    puts stderr "  VG_GCSA_LCP (gcsa lcp index)"
    puts stderr "  VG_GBWT     (gbwt haplotype paths: rpvg)"
    puts stderr "  VG_GBWT_RI  (gbwt index)"
    puts stderr "  VG_TXORIGIN_TSV (transcript origin: rpvg)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local star_index_dir = ref_root
setenv("STAR_INDEX_DIR", star_index_dir)
if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  VG_XG       (xg index file: mpmap, rpvg)\n")
    io.stderr:write("  VG_DIST     (dist index file: mpmap)\n")
    io.stderr:write("  VG_GCSA     (gcsa2 index file: mpmap, rpvg)\n")
    io.stderr:write("  VG_GCSA_LCP (gcsa lcp index)\n")
    io.stderr:write("  VG_GBWT     (gbwt haplotype paths: rpvg)\n")
    io.stderr:write("  VG_GBWT_RI  (gbwt index)\n")
    io.stderr:write("  VG_TXORIGIN_TSV (transcript origin: rpvg)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
