#!/usr/bin/bash
#WHATIS:GRCm39 RepeatMasker GTF
#URL:https://genome.ucsc.edu/cgi-bin/hgTables

#########################################################
# - https://genome.ucsc.edu/cgi-bin/hgTables?clade=mammal&org=Mouse&db=mm39&hgta_group=allTracks&hgta_track=rmsk&hgta_table=rmsk&hgta_regionType=genome&position=&hgta_outputType=gff&hgta_outFileName=mm39_rmsk.gtf&hgta_doTopSubmit=get+output
# Currently UCSC table browser requires a verification step (captcha) to download RMSK GTF for hg38
# So the file cannot be downloaded programmatically at this time.
##########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    cd "$target_dir"
    url="https://github.com/Justype/modules/releases/download/rmsk/mm39_rmsk.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "mm39_rmsk.gtf.gz" "$url"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the ref directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set RMSK_gtf_gz \$ref_root/mm39_rmsk.gtf.gz
setenv RMSK_GTF_GZ \$RMSK_gtf_gz

if { [module-info mode] == "load" && ![info exists env(SLURM_JOB_ID)] } {
    puts stderr "Available environment variables:"
    puts stderr "  RMSK_GTF_GZ  (rmsk gtf.gz)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local rmsk_gtf_gz = pathJoin(ref_root, "mm39_rmsk.gtf.gz")
setenv("RMSK_GTF_GZ", rmsk_gtf_gz)

if (mode() == "load" and os.getenv("SLURM_JOB_ID") == nil) then
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  RMSK_GTF_GZ  (rmsk gtf.gz)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         assembly/data-type (e.g. grch38/gencode-gtf)
# - version:          version (e.g. 41)
# - app_name_version: assembly/data-type/version (e.g. grch38/gencode-gtf/41)

# - target_base_dir:  modules/ref/assembly/data-type
# - target_dir:       modules/ref/assembly/data-type/version
# - script_path:      modules/ref_modulefiles/ref/assembly/data-type/version
# - tmp_dir:          tmp directory (modules/tmp/assembly/data-type/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main "$@"
