#!/usr/bin/bash
#DEPENDENCY:samtools/*
#WHATIS:GRCm39 reference genome FASTA
#URL:https://www.gencodegenes.org/mouse/

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    cd "$target_dir"

    url='https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M38/GRCm39.primary_assembly.genome.fa.gz'
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "GRCm39.primary_assembly.genome.fa.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    pigz_or_gunzip "GRCm39.primary_assembly.genome.fa.gz"

    print_stderr "Indexing ${YELLOW}${app_name_version}${NC} with samtools faidx"
    samtools faidx "GRCm39.primary_assembly.genome.fa"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the ref directory in modulefile[.lua]
    remove_default_dependencies "samtools"
    
    # add custom environment variables and functions to modulefile
    cat << EOF >> "${script_path}"
set genome_fasta \$ref_root/GRCm39.primary_assembly.genome.fa
setenv GENOME_FASTA \$genome_fasta

if { [module-info mode] == "load" && ![info exists env(SLURM_JOB_ID)] } {
    puts stderr "Available environment variables:"
    puts stderr "  GENOME_FASTA       (fasta file)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local genome_fasta = pathJoin(ref_root, "GRCm39.primary_assembly.genome.fa")
setenv("GENOME_FASTA", genome_fasta)

if (mode() == "load" and os.getenv("SLURM_JOB_ID") == nil) then
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  GENOME_FASTA       (fasta file)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         assembly/data-type (e.g. grch38/gencode-gtf)
# - version:          version (e.g. 41)
# - app_name_version: assembly/data-type/version (e.g. grch38/gencode-gtf/41)

# - target_base_dir:  modules/ref/assembly/data-type
# - target_dir:       modules/ref/assembly/data-type/version
# - script_path:      modules/ref_modulefiles/ref/assembly/data-type/version
# - tmp_dir:          tmp directory (modules/tmp/assembly/data-type/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
