#!/usr/bin/bash
#DEPENDENCY:grch38/genome/gencode
#DEPENDENCY:grch38/gtf/gencode47
#DEPENDENCY:star/2.7.11b
#WHATIS:STAR GRCh38 GENCODE47 index for read length 101
#URL:https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf

#########################################################
# If you want to build index for another annotation version,
#   1. copy the script to a new name, e.g., gencode49-151
#   2. change the dependencies to the new genome and transcriptome data (my script will autodetect the read length from the script name)
#   3. change the WHATIS line accordingly
#
# - https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
# - sjdbOverhang default value is 100
#########################################################

# Get the sequence length from the script name
script_name=$(basename "$0")
seq_len=${script_name##*-} # extract everything after the last hyphen
build_len=$((seq_len - 1))

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    pigz_or_gunzip_pipe "$ANNOTATION_GTF_GZ" > annotation.gtf
    
    print_stderr "Building STAR index for ${YELLOW}${app_name_version}${NC}"
    STAR --runThreadN $ncpu \
        --runMode genomeGenerate \
        --genomeDir "$target_dir" \
        --genomeFastaFiles "$GENOME_FASTA" \
        --sjdbGTFfile annotation.gtf \
        --sjdbOverhang $build_len
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the ref directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set star_index_dir \$ref_root
setenv STAR_INDEX_DIR \$star_index_dir
if { [module-info mode] == "load" && ![info exists ::env(SLURM_JOB_ID)] } {
    puts stderr "Available environment variables:"
    puts stderr "  STAR_INDEX_DIR   (STAR index directory: star alignment)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local star_index_dir = ref_root
setenv("STAR_INDEX_DIR", star_index_dir)
if (mode() == "load" and os.getenv("SLURM_JOB_ID") == nil) then
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  STAR_INDEX_DIR   (STAR index directory: star alignment)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         assembly/data-type (e.g. grch38/gencode-gtf)
# - version:          version (e.g. 41)
# - app_name_version: assembly/data-type/version (e.g. grch38/gencode-gtf/41)

# - target_base_dir:  modules/ref/assembly/data-type
# - target_dir:       modules/ref/assembly/data-type/version
# - script_path:      modules/ref_modulefiles/ref/assembly/data-type/version
# - tmp_dir:          tmp directory (modules/tmp/assembly/data-type/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
