#!/usr/bin/bash
#WHATIS:Template for building a module
#URL:

#########################################################
# Template for building a module (single executable)
# - You can change the url to the actual download link (with $version)
#########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    mkdir -p "$target_dir/bin"       # modules/apps/name/version/bin

    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    ## Add your download link here
    url="" # e.g. https://github.com/PacificBiosciences/skera/releases/download/v${version}/skera
    wget -nv -O "${target_dir}/bin/${app_name}" "$url"

    chmod +x "${target_dir}/bin/${app_name}"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # app_root is a special variable that points to the app directory in modulefile[.lua]
    
    # print_stderr "Adding ${BLUE}TEMPLATE_HOME${NC} environment variable"
    # echo "setenv TEMPLATE_HOME \$app_root" >> "${script_path}"
    # echo "setenv(\"TEMPLATE_HOME\", app_root)" >> "${script_path}.lua"

    # You can use remove_default_dependencies() function to remove unwanted dependencies
    # e.g. remove_default_dependencies "samtools"
    return 0
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/apps_modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main "$@"
