#!/usr/bin/bash
#WHATIS:GRCh38 RepeatMasker GTF

#########################################################
# - https://genome.ucsc.edu/cgi-bin/hgTables
# - https://genome.ucsc.edu/cgi-bin/hgTables?clade=mammal&org=Human&db=hg38&hgta_group=allTracks&hgta_track=rmsk&hgta_table=rmsk&hgta_regionType=genome&position=&hgta_outputType=gff&hgta_outFileName=hg38_rmsk.gtf&hgta_doTopSubmit=get+output
# Currently UCSC table browser requires a verification step (captcha) to download RMSK GTF for hg38
# So the file cannot be downloaded programmatically at this time.
#########################################################

install_app() {
    # mkdir -p "$target_base_dir"  # modules/apps/name
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    url="https://github.com/Justype/modules/releases/download/rmsk/hg38_rmsk.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "grch38_rmsk.gtf.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    gunzip "grch38_rmsk.gtf.gz"

    print_stderr "Moving files to target directory"
    mv "grch38_rmsk.gtf" "$target_dir/"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    
    # add custom environment variables and functions to modulefile
    cat << EOF >> "${script_path}"
set RMSK_gtf \$ref_root/grch38_rmsk.gtf
setenv RMSK_GTF \$RMSK_gtf

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    puts stderr "Available environment variables:"
    puts stderr "  RMSK_GTF  (rmsk gtf)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local rmsk_gtf = pathJoin(ref_root, "grch38_rmsk.gtf")
setenv("RMSK_GTF", rmsk_gtf)

if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  RMSK_GTF  (rmsk gtf)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
