#!/usr/bin/bash
#WHATIS:GRCh38 reference genome GTF for GENCODE 47

#########################################################
# GRCh38 reference genome GTF
# - https://www.gencodegenes.org/human/
#########################################################

gencode_version="47"

install_app() {
    # mkdir -p "$target_base_dir"  # modules/apps/name
    mkdir -p "$target_dir"       # modules/apps/name/version
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    url="https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_${gencode_version}/gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    gunzip "gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz"

    print_stderr "Moving files to target directory"
    mv "gencode.v${gencode_version}.primary_assembly.annotation.gtf" "$target_dir/"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    
    # add custom environment variables and functions to modulefile
    cat << EOF >> "${script_path}"
set annotation_gtf \$ref_root/gencode.v${gencode_version}.primary_assembly.annotation.gtf
setenv ANNOTATION_GTF \$annotation_gtf

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    # only display message when in terminal
    if {[info exists env(TERM)] && \$env(TERM) != "dumb"} {
        puts stderr "Available environment variables:"
        puts stderr "  ANNOTATION_GTF  (annotation gtf)"
    }
}
EOF

    cat << EOF >> "${script_path}.lua"
local annotation_gtf = pathJoin(ref_root, "gencode.v${gencode_version}.primary_assembly.annotation.gtf")
setenv("ANNOTATION_GTF", annotation_gtf)

if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    -- only display message when in terminal
    if os.getenv("TERM") and os.getenv("TERM") ~= "dumb" then
        io.stderr:write("Available environment variables:\n")
        io.stderr:write("  ANNOTATION_GTF  (annotation gtf)\n")
    end
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
