#!/usr/bin/bash
#WHATIS:GRCm39 reference genome GTF for GENCODE M33

#########################################################
# - https://www.gencodegenes.org/mouse/
#########################################################

# Get the gencode version from the script name
script_name=$(basename "$0")
gencode_version="${script_name##*-gencode}"

install_app() {
    mkdir -p "$target_dir"       # modules/apps/name/version
    cd "$target_dir"
    url="https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_${gencode_version}/gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    pigz_or_gunzip "gencode.v${gencode_version}.primary_assembly.annotation.gtf.gz"
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    
    # add custom environment variables and functions to modulefile
    cat << EOF >> "${script_path}"
set annotation_gtf \$ref_root/gencode.v${gencode_version}.primary_assembly.annotation.gtf
setenv ANNOTATION_GTF \$annotation_gtf

if { [module-info mode] == "load" } {
    puts stderr "\[\$current_datetime\] Loading module \$ref_full_name"
    puts stderr "Available environment variables:"
    puts stderr "  ANNOTATION_GTF       (annotation gtf file)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local annotation_gtf = pathJoin(ref_root, "gencode.v${gencode_version}.primary_assembly.annotation.gtf")
setenv("ANNOTATION_GTF", annotation_gtf)

if (mode() == "load") then
    io.stderr:write(string.format("[%s] Loading module %s\n", current_datetime, ref_full_name))
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  ANNOTATION_GTF       (annotation gtf file)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         name     of the app
# - version:          version  of the app
# - app_name_version: name/version

# - target_base_dir:  modules/apps/name
# - target_dir:       modules/apps/name/version
# - script_path:      modules/modulefiles/name/version
# - tmp_dir:          tmp directory (modules/tmp/name/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
