#!/usr/bin/bash
#DEPENDENCY:grch38/genome/gencode
#DEPENDENCY:grch38/transcript/gencode44
#DEPENDENCY:salmon/1.10.3
#WHATIS:Salmon GRCh38 GENCODE 44 index for transcript quantification
#URL:https://combine-lab.github.io/salmon/

#########################################################
# If you want to build index for another annotation version,
#   1. copy the script to a new name, e.g., salmon-grch38-gencode49
#   2. change the dependencies to the new genome and transcriptome data
#   3. change the WHATIS line accordingly
#
# - https://combine-lab.github.io/salmon/
# - https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode
#########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    print_stderr "Appending genome to transcriptome and generating decoys..."

    pigz_or_gunzip_pipe "$TRANSCRIPT_FASTA_GZ" > gentrome.fa
    cat "$GENOME_FASTA" >> gentrome.fa

    if [ -f "${GENOME_FASTA}.fai" ]; then
        print_stderr "Using existing ${YELLOW}${GENOME_FASTA}.fai${NC} to generate decoys"
        cat "${GENOME_FASTA}.fai" | cut -f 1 > decoys.txt
    else
        print_stderr "Using fastq header lines to generate decoys"
        cat "$GENOME_FASTA" | \
            grep "^>" | \
            cut -d " " -f 1 | \
            sed 's/^>//' \
            > decoys.txt
    fi
    
    print_stderr "Building Salmon index for ${YELLOW}${app_name_version}${NC}"
    salmon index \
        -p $ncpu \
        -t gentrome.fa \
        -d decoys.txt \
        -i "$target_dir" \
        --gencode
}

special_modulefiles() {
    # Any additional modulefile operations: add environment variables, aliases, etc.
    # ref_root is a special variable that points to the app directory in modulefile[.lua]
    cat << EOF >> "${script_path}"
set salmon_index_dir \$ref_root
setenv SALMON_INDEX_DIR \$salmon_index_dir
if { [module-info mode] == "load" && ![info exists env(SLURM_JOB_ID)] } {
    puts stderr "Available environment variables:"
    puts stderr "  SALMON_INDEX_DIR       (Salmon index directory)"
}
EOF

    cat << EOF >> "${script_path}.lua"
local salmon_index_dir = ref_root
setenv("SALMON_INDEX_DIR", salmon_index_dir)
if (mode() == "load" and os.getenv("SLURM_JOB_ID") == nil) then
    io.stderr:write("Available environment variables:\n")
    io.stderr:write("  SALMON_INDEX_DIR       (Salmon index directory)\n")
end
EOF
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK

# - app_name:         assembly/data-type (e.g. grch38/gencode-gtf)
# - version:          version (e.g. 41)
# - app_name_version: assembly/data-type/version (e.g. grch38/gencode-gtf/41)

# - target_base_dir:  modules/ref/assembly/data-type
# - target_dir:       modules/ref/assembly/data-type/version
# - script_path:      modules/ref_modulefiles/ref/assembly/data-type/version
# - tmp_dir:          tmp directory (modules/tmp/assembly/data-type/version)

RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color

if ! [ -d build-scripts ]; then
    printf "Please run this script under ${RED}modules${NC} directory.\n" 1>&2
    printf "And make sure you have your scripts in build-scripts folder.\n" 1>&2
    printf "    e.g. bash build-scripts/sra-tools/3.1.1\n" 1>&2
    exit 1
fi

source "build-scripts/common.sh"
main $@
